In [1]:
import numpy as np
import pandas as pd

In [2]:
rng = np.random.default_rng(616)

In [3]:
inventory = rng.integers(0, 100, 10)

In [69]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [5]:
inventory - 20

array([19, 19, 73, 66, 28, 26, 28, 10, -9, 37], dtype=int64)

In [6]:
(inventory /2).dtype

dtype('float64')

In [7]:
price = (rng.random(10)*10).round(2)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [8]:
(price*inventory).sum()

2520.4700000000003

In [9]:
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [10]:
[x*2 for x in inventory_list]

[78, 78, 186, 172, 96, 92, 96, 60, 22, 114]

In [11]:
[x*y for x, y in zip(inventory_list,price)]

[34.71,
 343.98,
 680.76,
 629.52,
 269.76,
 156.4,
 30.240000000000002,
 107.1,
 22.33,
 245.67]

In [12]:
my_array = np.arange(20)

In [13]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
my_array[my_array%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
mask = my_array%2!=0

In [16]:
my_array[mask]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
even_odd = np.array(['even', 'odd']*10)

In [18]:
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [19]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [20]:
even_odd[even_odd != "even"]

array(['odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd',
       'odd'], dtype='<U4')

In [21]:
my_array[even_odd != "odd"] = 22
my_array

array([22,  1, 22,  3, 22,  5, 22,  7, 22,  9, 22, 11, 22, 13, 22, 15, 22,
       17, 22, 19])

In [22]:
my_array[1]=100000

In [23]:
my_array

array([    22, 100000,     22,      3,     22,      5,     22,      7,
           22,      9,     22,     11,     22,     13,     22,     15,
           22,     17,     22,     19])

In [24]:
mask = (my_array>=100000) | (my_array==22)
my_array[mask]

array([    22, 100000,     22,     22,     22,     22,     22,     22,
           22,     22,     22])

In [25]:
mask = (my_array>100000) | (my_array!=22)
my_array[mask]

array([100000,      3,      5,      7,      9,     11,     13,     15,
           17,     19])

In [26]:
np.where(my_array - 5 ==0, "Not available", "Available")

array(['Available', 'Available', 'Available', 'Available', 'Available',
       'Not available', 'Available', 'Available', 'Available',
       'Available', 'Available', 'Available', 'Available', 'Available',
       'Available', 'Available', 'Available', 'Available', 'Available',
       'Available'], dtype='<U13')

In [27]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [28]:
inventory.sum()

497

In [29]:
inventory.mean()

49.7

In [30]:
hello=np.array([1,6])

In [31]:
hello

array([1, 6])

In [32]:
hello.mean()

3.5

In [33]:
hello.std()

2.5

In [34]:
price.reshape(5,2)

array([[0.89, 8.82],
       [7.32, 7.32],
       [5.62, 3.4 ],
       [0.63, 3.57],
       [2.03, 4.31]])

In [35]:
prices = np.arange(1,11)

In [36]:
new_prices=prices.reshape(5,2)
new_prices

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:

new_prices.sum(axis=0)

array([25, 30])

In [41]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [42]:
pda = pd.Series(array)

In [43]:
pda

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [53]:
series = pd.Series(np.array([7,5,6,5]), name="series")

In [57]:
mean = series.values
mean

array([7, 5, 6, 5])

In [58]:
mean.mean()

5.75

In [62]:
series.index = [10,20,30,40]
series

10    7
20    5
30    6
40    5
Name: series, dtype: int32

In [68]:
series.sum()

23

In [67]:
series.astype("float").mean()

5.75

In [65]:
series.astype("bool")

10    True
20    True
30    True
40    True
Name: series, dtype: bool

In [66]:
series.astype("object")

10    7
20    5
30    6
40    5
Name: series, dtype: object

In [71]:
series.info(show_counts=True)

<class 'pandas.core.series.Series'>
Index: 4 entries, 10 to 40
Series name: series
Non-Null Count  Dtype
--------------  -----
4 non-null      int32
dtypes: int32(1)
memory usage: 48.0 bytes
